version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-29
    working_directory: ~/project
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Install Flutter
          command: |
            git clone https://github.com/flutter/flutter.git -b stable --depth 1
            export PATH="$PATH:`pwd`/flutter/bin"
      - run:
          name: Install Dependencies
          command: flutter packages get
      - run:
          name: Build APK
          command: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
